
class AtBatOutcome:
    BALL = 'ball'
    BB = 'base on balls'
    CS = 'called strike'
    CSO = 'strikes out  looking'
    SWS = 'swinging strike'
    SWSO = 'strikes out  swinging'
    FB = 'foul ball'
    BFB = 'bunted foul'
    FO = 'fly out'
    GO = 'ground out'
    FC = 'fielders choice'
    GODP = 'grounds into double play'
    ROE = 'reached on error'
    RVE = 'reached via error'
    SINGLE = 'single'
    DOUBLE = 'double'
    TRIPLE = 'triple'
    HR = 'home run'
    SACBUNT = 'sac bunt'
    OUT = 'out'
