
class AtBatOutcome:
    BALL = 'ball'
    BB = 'base on balls'
    IBB = 'intentional walk'
    HB = 'hit by pitch'
    CS = 'called strike'
    CSO = 'strikes out  looking'
    SWS = 'swinging strike'
    SWSO = 'strikes out  swinging'
    BUNTMISSED = 'bunt missed!'
    BUNTMISSED_SO = 'bunt missed, strikeout!'
    FB = 'foul ball'
    BFB = 'bunted foul'
    FO = 'fly out'
    PO = 'popout'
    GO = 'ground out'
    GOS = 'grounds out'
    FC = 'fielders choice'
    GOFC = 'grounds into fielders choice'
    GODP = 'grounds into double play'
    GOTP = 'grounds into triple play'
    ROE = 'reached on error'
    RVE = 'reached via error'
    RCI = 'reaches on catchers interference'
    SINGLE = 'single'
    DOUBLE = 'double'
    TRIPLE = 'triple'
    HR = 'home run'
    SACBUNT = 'sac bunt'
    BUNTFORHIT = 'bunt for hit'
    BUNTFO = 'bunt - flyout'
    SQZBUNT = 'squeeze bunt'
    SQZ_HOME_RUNNER_OUT = 'play home, runner out,'
    SQZ_HOME_RUNNER_SAFE = 'play home, runner scores,'
    SQZ_FIRST_OUT = 'play at first, runner scores, batter out'
    SQZ_FIRST_SAFE = 'play at first, runner scores, batter safe'
    SQZ_BATTER_SAFE = 'batter safe'
    SAFE = 'safe'
    OUT = 'out'
    LTP = 'lines into triple play'


