from enum import Enum


class Team(Enum):

    # GUBA
    BEI = 'Beijing Bison'
    BOG = 'Bogota Toros'
    BDX = 'Bordeaux Vignerons'
    CC = 'Cape Cod Hooks'
    CHC = 'Christchurch Crusaders'
    CIN = 'Cincinnati Showboats'
    DUB = 'Dublin Shamrocks'
    GRE = 'Greenville Moonshiners'
    HON = 'Honolulu Island Kings'
    HOU = 'Houston Orbits'
    KC = 'Kansas City Monarchs'
    LON = 'London Spitfires'
    MOS = 'Moscow Enforcers'
    NSH = 'Nashville Sounds'
    PHI = 'Philadelphia Brewers'
    SA = 'San Antonio Outlaws'
    SJ = 'San Juan Tiburones'
    SD = 'Santo Domingo Tortugas'
    SP = 'Sao Paulo Oncas'
    SEA = 'Seattle Admirals'
    SEO = 'Seoul Crushers'
    SYD = 'Sydney Marauders'
    TOR = 'Toronto Beavers'

    # AAA
    CAR = 'Caracas Roughnecks'
    MAU ='Maui Tsunami'
    AVA = 'Avangard Omsk'
    MON = 'Montreal Royales'
    CLG = 'Calgary Dinos'
    POR ='Portland Herons'
    SPR = 'Springfield Cardinals'
    NM = 'New Mexico Diablos'
    PAP = 'Port-au-Prince Liberators'
    TA = 'Tel Aviv Stars'
    SCR ='Scranton Electrics'
    BIR = 'Birmingham Bandits'
    MIL = 'Milwaukee Choppers'
    PAR = 'Paris Impressionnistes'
    WEL ='Wellington Warriors'
    MAI = 'Maine Moose'
    MEL = 'Melbourne Aces'
    ODE ='Odessa Drillers'
    LIM = 'Limerick Leprechauns'
    JUA = 'Juarez Indios'
    LA = 'Los Angeles Quakes'
    BUS = 'Busan Seagulls'
    LON ='London ICF'
    SHA = 'Shanghai Snakes'

    # AA
    'Mexico City Diablos Rojos'
    'Riyadh Red Crescents'
    'Markham Bears'
    'Pago Pago Wildcats'
    'Dover Patriots'
    'Dynamo Moscow'
    'Austin Riverbats'
    'Bellingham Bandits'
    'Derry Pints'
    'Invercargill Seals'
    GUA = 'Guangzhou Tigers'
    'Marseille Predicatuers'
    'Palm Beach Cardinals'
    'Columbus (OH) Legends'
    'Vancouver Mounties'
    'Brisbane Bandits'
    'Incheon Air'
    'Cuban Revolution'
    'Chelsea Headhunters'
    'Lexington Minutemen'
    'Omaha Barnstormers'
    'Orlando Stars'
    'Chihuahua Chihuahuas'
    'Bethlehem Steelers'

    # A
    'Havana Perfectos'
    'Reims Rois'
    'Bend Cascades'
    'Auckland Warriors'
    'Amman Kings'
    ZHE = 'Zhengzhou Elephants'
    'Ak Bars Kazan'
    'Pearl City Snappers'
    'Killarney Kingsmen'
    'St Louis Spirits'
    'Edmonton Ooks'
    'Rotorua Firewalkers'
    'Hackensack Bulls'
    'Quad City River Bandits'
    'Perth Heat'
    'Daegu Lions'
    'Portland Timbers'
    'Barbados Sea Dogs'
    'Newcastle Gremlins'
    'Midland Oilers'
    'Louisville Nine'
    'Reading Railers'
    'Shreveport Pirates'
    'Rhode Island Whitecaps'

    # SA
    'Taupo Kiwis'
    'Lima Kings'
    'Khartoum Crocodiles'
    'Ashland Bards'
    'Kona Tropics'
    'Belize Criollos'
    'Las Cruces Sun Kings'
    'Charlotte Generals'
    'Adelaide Bite'
    'Quebec Nordiques'
    'Cork Saints'
    'Medellin Cartel'
    'Toulouse Aviatuers'
    MAN = 'Manchuria Moon Bears'
    'San Antonio Bandits'
    'CSKA Moscow'
    'Erie Lakers'
    'Sao Paulo River Monsters'
    'Batavia Muckdogs'
    'Daejeon Eagles'
    'Port Royal Privateers'
    'Hull City Psychos'
    'Brooklyn Cyclones'
    'Seattle Herons'

    # Rookie
    'Johnson City Cardinals'
    'Halawa Ocean'
    'Lancaster Red Roses'
    'Arrowtown Orcs'
    'Miami Silver Sox'
    'Ponce Leones'
    'Rushmore Bee Keepers Society'
    'Frankfurt Fette Hennen'
    'Mobile Biscuit Whompers'
    TIB = 'Tibet Wolves'
    'Buffalo Bisons'
    'John Day Fossils'
    'Detroit Hot Rods'
    'Iqaluit Wolves'
    'Caen Liberateurs'
    'Sunderland Seaburn Casuals'
    'Metallurg Magnitogorsk'
    'Tallahassee Sabres'
    'Waterford Reds'
    'Darwin Wranglers'
    'Barranquilla Blaze'
    'Vermont Lake Monsters'
    'Anchorage Black Bears'
    'Gwangju Poets'


    @staticmethod
    def find_team_by_abbr(abbr):
        for team in Team:
            if team.name == abbr:
                return team

    @staticmethod
    def find_team_by_name(name):
        for team in Team:
            if str(team.value).strip().lower().__eq__(name.strip().lower()):
                return team
