from enum import Enum


class Team(Enum):

    # RDL
    NR = 'New Ruksburgh Red Squirrels'
    TRA = 'Traston Robins'
    POR = 'Port Berth Armada'
    RAU = 'Raupo Kings'
    NB = 'New Bludvist Ravens'
    CSB = 'Crescent Bay Sharks'
    StG = 'St. Grouix Islanders'
    TID = 'Tidepool Gulls'
    EDG = 'Eden Garden Appleseeds'
    SIL = 'Siltston Neptunes'
    PLU = 'Plumbua Warriors'
    SRF = 'Surf City Beacons'
    KIT = 'Kitter Tigers'
    TRO = 'Trome Knights'
    KOL = 'Koldonia Wizards'
    SC = 'Star City Emeralds'
    BIL = 'Biltanore Stone Crabs'
    LRF = 'Lockrun Forest Bears'
    RR = 'Rustic River Barons'
    HAI = 'Hainesville Hooligans'
    DEP = 'Deepwood Lumberjacks'
    DEA = 'Deadwood Wranglers'
    HP = 'High Point Miners'
    TRE = 'Trelly Springs Bells'

    # AAA
    MOR = 'Morburn Bells'
    CLF = 'Cliffhurst Hornets'
    BRE = 'Brecon Bluebirds'
    HOL = 'Hollow Beach Blue Claws'
    WHV = 'Whitevale Wolverines'
    VER = 'Vertedge Surge'
    DLG = 'Delledge Owls'
    ORT = 'Ortown Angels'
    MAR = 'Marbleview Bishops'
    PTA = 'Port Ampton Sea Dogs'
    PRC = 'Prancer Bay Hammerheads'
    LIK = 'Likoa Volcanoes'
    ALL = 'Alloway City River Kings'
    DEL = 'Del Yokula Archers'
    AEL = 'Aelhurst Red Hawks'
    SGT = 'St. Gitters Friars'
    HAM = 'Hamilton Spartans'
    SGD = 'South Gradenton Black Bears'
    BEN = 'Bendersbow North Stars'
    MER = 'Mercer Beavers'
    TRK = 'Troksburgh Lancers'
    GOL = 'Golters Peak Silver Sox'
    TRD = 'Treading Bay Bears'
    CRW = 'Carew Bulldogs'

    # AA
    RED = 'Redlyn Chargers'
    GOO = 'Goodwick Renegades'
    MIL = 'Milwall Hens'
    ORK = 'Orick Rhinos'
    FTR = 'Fort Reppit Lions'
    DUN = 'Dunnels Corner Oilers'
    HLD = 'Holder Privateers'
    MAS = 'Masone Beagles'
    TAT = 'Tattershall Titans'
    GRF = 'Griffin City Pilots'
    HAR = 'Harborsmouth Orcas'
    ISO = 'Port Iso Ocean'
    KRE = 'Krelmar Crows'
    STR = 'Storewell Bobcats'
    GRE = 'Greenshore Snappers'
    BRD = 'Brondby Falcons'
    TAD = 'Tadler Wildcats'
    CMY = 'Cumby Mallards'
    NJ = 'New Jansen Marlins'
    STE = 'Steinert Blacksox'
    SMI = 'Smithton Marshals'
    HOT = 'Holten Sting'
    ASH = 'Ashburton Steelhounds'
    KAL = 'Kallo Hawks'

    # A
    HIG = 'Higgston Cyclones'
    MON = 'Monmouth Clippers'
    GRY = 'Greywall Hawks'
    WOD = 'Woodlyn Timberjacks'
    THA = 'Thayne Crusaders'
    REN = 'Renton Green Sox'
    VAL = 'Valle Slayers'
    TAL = 'Talat Cobras'
    FC = 'Flint City Vikings'
    BOL = 'Bolsdale Beacons'
    DUK = 'Dunkleys Defenders'
    TAV = 'Tavora Railers'
    GRT = 'Gretahaven Foresters'
    ANW = 'Andwil Flyers'
    LTK = 'Lightkeep Tides'
    HAL = 'Halaga Bulls'
    ADM = 'Adamston Lagers'
    CC = 'Camp Crook Rangers'
    NA = 'New Augusta Jackals'
    GM = 'Glen Marchwood Canaries'
    SPH = 'Springhill Possums'
    RV = 'Rutters Valley Grasshoppers'
    STA = 'Stratton Twins'
    EVB = 'Everberg Ice Cats'

    # Rookies
    NOR = 'Norvelt Green Hawks'
    ORH = 'Orhollow Water Wolves'
    MAP = 'Mapledell Swallows'
    PER = 'Peerson Whitecaps'
    PLC = 'Port LaCella Breakers'
    RCF = 'Redcliffe Condors'
    PUR = 'Purello Roses'
    ASB = 'Ashby Mudcats'
    DRY = 'Drayton Dragons'
    BWC = 'Berwick Devils'
    BH = 'Brown Hills Tomcats'
    FT = 'Fort Travers River Sharks'
    FA = 'Fort Aston Spiders'
    TUC = 'Tucino Phantoms'
    VSP = 'Visp City Venom'
    TUL = 'Tulletsport Bucs'
    McG = 'McGwire Blackbirds'
    FAL = 'Fort Allers Sabres'
    FLE = 'Fletcher 49ers'
    TUR = 'Turon Grays'
    AUD = 'Auderville Aces'
    LEI = 'Leiston Hounds'
    DAN = 'Dancaster Lynx'
    EST = 'Estercrest Purple Knights'

    BEI = 'Beijing Bison'
    BOG = 'Bogota Toros'
    BDX = 'Bordeaux Vignerons'
    CC_GUBA = 'Cape Cod Hooks'
    CHC = 'Christchurch Crusaders'
    CIN = 'Cincinnati Showboats'
    DUB = 'Dublin Shamrocks'
    GRE_GUBA = 'Greenville Moonshiners'
    HON = 'Honolulu Island Kings'
    HOU = 'Houston Orbits'
    KC = 'Kansas City Monarchs'
    LON = 'London Spitfires'
    MOS = 'Moscow Enforcers'
    NSH = 'Nashville Sounds'
    PHI = 'Philadelphia Brewers'
    SA = 'San Antonio Outlaws'
    SJ = 'San Juan Tiburones'
    SD = 'Santo Domingo Tortugas'
    SP = 'Sao Paulo Oncas'
    SEA = 'Seattle Admirals'
    SEO = 'Seoul Crushers'
    SYD = 'Sydney Marauders'
    TOR = 'Toronto Beavers'

    SHA = 'Shanghai Snakes'
    GUA = 'Guangzhou Tigers'
    ZHE = 'Zhengzhou Elephants'
    MAN = 'Manchuria Moon Bears'
    TIB = 'Tibet Wolves'

    @staticmethod
    def find_team_by_abbr(abbr):
        for team in Team:
            if team.name == abbr:
                return team

    @staticmethod
    def find_team_by_name(name):
        for team in Team:
            if str(team.value).strip().lower().__eq__(name.strip().lower()):
                return team
