from enum import Enum


class Team(Enum):

    # GUBA
    BEI = 'Beijing Bison'
    BOG = 'Bogota Toros'
    BDX = 'Bordeaux Vignerons'
    CC = 'Cape Cod Hooks'
    CHC = 'Christchurch Crusaders'
    CIN = 'Cincinnati Showboats'
    DUB = 'Dublin Shamrocks'
    GRE = 'Greenville Moonshiners'
    HON = 'Honolulu Island Kings'
    HOU = 'Houston Orbits'
    KC = 'Kansas City Monarchs'
    LON = 'London Spitfires'
    MOS = 'Moscow Enforcers'
    NSH = 'Nashville Sounds'
    PHI = 'Philadelphia Brewers'
    SA = 'San Antonio Outlaws'
    SJ = 'San Juan Tiburones'
    SD = 'Santo Domingo Tortugas'
    SP = 'Sao Paulo Oncas'
    SEA = 'Seattle Admirals'
    SEO = 'Seoul Crushers'
    SYD = 'Sydney Marauders'
    TOR = 'Toronto Beavers'

    # AAA
    CAR = 'Caracas Roughnecks'
    MAU = 'Maui Tsunami'
    AVA = 'Avangard Omsk'
    MON = 'Montreal Royales'
    CLG = 'Calgary Dinos'
    POR = 'Portland Herons'
    SPR = 'Springfield Cardinals'
    NM = 'New Mexico Diablos'
    PAP = 'Port-au-Prince Liberators'
    TA = 'Tel Aviv Stars'
    SCR = 'Scranton Electrics'
    BIR = 'Birmingham Bandits'
    MIL = 'Milwaukee Choppers'
    PAR = 'Paris Impressionnistes'
    WEL = 'Wellington Warriors'
    MAI = 'Maine Moose'
    MEL = 'Melbourne Aces'
    ODE = 'Odessa Drillers'
    LIM = 'Limerick Leprechauns'
    JUA = 'Juarez Indios'
    LA = 'Los Angeles Quakes'
    BUS = 'Busan Seagulls'
    LON_AA = 'London ICF'
    SHA = 'Shanghai Snakes'

    # AA
    MC = 'Mexico City Diablos Rojos'
    RIY = 'Riyadh Red Crescents'
    MAR_AA_B = 'Markham Bears'
    PP = 'Pago Pago Wildcats'
    DOV = 'Dover Patriots'
    DYN = 'Dynamo Moscow'
    AUS = 'Austin Riverbats'
    BEL = 'Bellingham Bandits'
    DER = 'Derry Pints'
    INV = 'Invercargill Seals'
    GUA = 'Guangzhou Tigers'
    MAR_AA_P = 'Marseille Predicatuers'
    PB = 'Palm Beach Cardinals'
    COL = 'Columbus (OH) Legends'
    VAN = 'Vancouver Mounties'
    BSB = 'Brisbane Bandits'
    ICH = 'Incheon Air'
    CUB = 'Cuban Revolution'
    CHL = 'Chelsea Headhunters'
    LEX = 'Lexington Minutemen'
    OMA = 'Omaha Barnstormers'
    ORL = 'Orlando Stars'
    CHI = 'Chihuahua Chihuahuas'
    BTH = 'Bethlehem Steelers'

    # A
    HAV = 'Havana Perfectos'
    REI = 'Reims Rois'
    BEN = 'Bend Cascades'
    AUK = 'Auckland Warriors'
    AMM = 'Amman Kings'
    ZHE = 'Zhengzhou Elephants'
    ABK = 'Ak Bars Kazan'
    PC = 'Pearl City Snappers'
    KIL = 'Killarney Kingsmen'
    SLS = 'St Louis Spirits'
    EDM = 'Edmonton Ooks'
    ROT = 'Rotorua Firewalkers'
    HAC = 'Hackensack Bulls'
    QC = 'Quad City River Bandits'
    PER = 'Perth Heat'
    DAE = 'Daegu Lions'
    POR_A = 'Portland Timbers'
    BAR = 'Barbados Sea Dogs'
    NEW = 'Newcastle Gremlins'
    MID = 'Midland Oilers'
    LOU = 'Louisville Nine'
    REA = 'Reading Railers'
    SHR = 'Shreveport Pirates'
    RI = 'Rhode Island Whitecaps'

    # SA
    TAU = 'Taupo Kiwis'
    LIM_SA = 'Lima Kings'
    KHA = 'Khartoum Crocodiles'
    ASH = 'Ashland Bards'
    KON = 'Kona Tropics'
    BEL_SA = 'Belize Criollos'
    LC = 'Las Cruces Sun Kings'
    CHA = 'Charlotte Generals'
    ADL = 'Adelaide Bite'
    QUE = 'Quebec Nordiques'
    COR = 'Cork Saints'
    MED = 'Medellin Cartel'
    TOU = 'Toulouse Aviatuers'
    MAN = 'Manchuria Moon Bears'
    SA_SA = 'San Antonio Bandits'
    CSK = 'CSKA Moscow'
    ERI = 'Erie Lakers'
    SAO = 'Sao Paulo River Monsters'
    BTV = 'Batavia Muckdogs'
    DAE_SA = 'Daejeon Eagles'
    PR = 'Port Royal Privateers'
    HC = 'Hull City Psychos'
    BRK = 'Brooklyn Cyclones'
    SEA_SA = 'Seattle Herons'

    # Rookie
    JC = 'Johnson City Cardinals'
    HAL = 'Halawa Ocean'
    LAN = 'Lancaster Red Roses'
    ARR = 'Arrowtown Orcs'
    MIA = 'Miami Silver Sox'
    PON = 'Ponce Leones'
    BKS = 'Rushmore Bee Keepers Society'
    FRK = 'Frankfurt Fette Hennen'
    MOB = 'Mobile Biscuit Whompers'
    TIB = 'Tibet Wolves'
    BUF = 'Buffalo Bisons'
    JD = 'John Day Fossils'
    DET = 'Detroit Hot Rods'
    IQA = 'Iqaluit Wolves'
    CAE = 'Caen Liberateurs'
    SUN = 'Sunderland Seaburn Casuals'
    MET = 'Metallurg Magnitogorsk'
    TAL = 'Tallahassee Sabres'
    WAT = 'Waterford Reds'
    DAR = 'Darwin Wranglers'
    BAR_R = 'Barranquilla Blaze'
    VER = 'Vermont Lake Monsters'
    ANC = 'Anchorage Black Bears'
    GWA = 'Gwangju Poets'

    @staticmethod
    def find_team_by_abbr(abbr):
        for team in Team:
            if team.name == abbr:
                return team

    @staticmethod
    def find_team_by_name(name):
        for team in Team:
            if str(team.value).strip().lower().__eq__(name.strip().lower()):
                return team
